[general]
import = [ "gruvbox_dark.toml" ]

[font]
normal = { family = "BlexMono Nerd Font" }
bold = { family = "BlexMono Nerd Font" }
italic = { family = "BlexMono Nerd Font" }
bold_italic = { family = "BlexMono Nerd Font" }
