#!/usr/bin/env zsh


if [[ -z $STOW_FOLDERS ]]; then
  # STOW_FOLDERS="bin\\.local/bin kitty\\.config/kitty nvim\\.config/nvim tmux\\ zsh\\"
  # STOW_FOLDERS="bin\\.local/bin kitty\\.config/kitty nvim\\.config/nvim tmux\\ zsh\\ npm\\"
  STOW_FOLDERS="npm\\"
fi

if [[ -z $DOTFILES ]]; then
    DOTFILES=$HOME/.dotfiles
fi


pushd $DOTFILES

echo $STOW_FOLDERS


for pair in $(echo $STOW_FOLDERS | sed "s/,/ /g")
do
    folder="${pair%%\\*}"
    dest="${pair##*\\}"

    mkdir ~/$dest 2> /dev/null

    echo "stow $folder to $dest"

    # error=$((stow -R -t ~/$dest $folder) 2>&1 >/dev/null)

    stow -t ~/$dest $folder
done

popd

