#!/usr/bin/env zsh

pushd $DOTFILES

echo $STOW_FOLDERS

for pair in $(echo $STOW_FOLDERS | sed "s/,/ /g")
do
    folder="${pair%%\\*}"
    dest="${pair##*\\}"

    mkdir ~/$dest

    echo "stow $folder to $dest"
    stow -t ~/$dest $folder
done

popd

